baseURL = "https://lex00.github.io/wetwire-observability-go/"
languageCode = "en-us"
title = "Wetwire Observability"
theme = "wetwire"

# Clean URLs
[permalinks]
  [permalinks.page]
    '/' = '/:slug/'
  [permalinks.section]
    '/' = '/:slug/'

# Syntax highlighting
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main menu
[menus]
  [[menus.main]]
    name = "CLI"
    pageRef = "/cli"
    weight = 10
  [[menus.main]]
    name = "Quick Start"
    pageRef = "/quick-start"
    weight = 20
  [[menus.main]]
    name = "Examples"
    pageRef = "/examples"
    weight = 30
  [[menus.main]]
  [[menus.main]]
    name = "FAQ"
    pageRef = "/faq"
    weight = 50
  [[menus.main]]
    name = "Source"
    url = "https://github.com/lex00/wetwire-observability-go"
    weight = 60
